menu:
    - 
        name: 'Home' 
        link: ''
    -
        name: 'Blog'
        link: 'blog'
    -
        name: 'Contattami'
        link: 'contattami'
    -
        name: 'Portfolio'
        link: 'portfolio'

disqus:
    shortname: leonardofontana
